#!/bin/bash

wget https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.12%2B7/OpenJDK11U-jdk_x64_linux_hotspot_11.0.12_7.tar.gz
tar xf OpenJDK11U-jdk_x64_linux_hotspot_11.0.12_7.tar.gz

# wget https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u422-b05/OpenJDK8U-jre_x64_linux_hotspot_8u422b05.tar.gz
# tar xf OpenJDK8U-jre_x64_linux_hotspot_8u422b05.tar.gz

pushd .
cd jdk-11.0.12+7
# cd jdk8u422-b05-jre/
export PATH="${PWD}/bin:${PATH}"
popd
